name: kube-linstor
description: Linstor Controller and Satellites for Kubernetes
version: v1.7.1-2
keywords:
  - linstor
  - drbd
  - storage
  - csi
home: https://github.com/kvaps/kube-linstor
sources:
  - https://hub.docker.com/r/kvaps/linstor-controller
  - https://hub.docker.com/r/kvaps/linstor-satellite
maintainers:
  - name: kvaps
    email: kvapss@gmail.com
