name: linstor
description: Containerized LINSTOR SDS for Kubernetes, ready for production use,
version: 1.7.2
appVersion: 1.7.2
keywords:
  - linstor
  - drbd
  - storage
  - csi
home: https://github.com/kvaps/kube-linstor
sources:
  - https://hub.docker.com/r/kvaps/linstor-controller
  - https://hub.docker.com/r/kvaps/linstor-satellite
maintainers:
  - name: kvaps
    email: kvapss@gmail.com
